training:
  name: line_2stage_class_2
  batch_size: 32
  learning_rate: 0.01
  momentum: 0.9
  alpha_reg: 100
  alpha_sigma: 0
  gpu_list: [0]
  epochs: 5000

dataset:
  path: ~/datasets/structure_core_unity_slice_100_35
  is_npy: True
  workers: 8
  tgt_res: [ 1216, 896 ]
  slice_in:
    start: 100
    height: 128
  slice_out:
    start: 50
    height: 64

backbone:
  load_file: ""
  name: Backbone2
  lines: 1
  slices: 1
  channels: [16, 32, 64]
  channels2: [64, 64, 64, 64]

regressor:
  load_file: ""
  name: Regv3
  ch_in: 64
  lines: 1
  bb: []
  classes: [16, 14, 12]
  padding: [0, 1, 2]
  class_bb: [[16], [16], [16]]
  superclasses: 168
  ch_reg: [32]
  msk: [16, 8]
  regress_neighbours: 1

