training:
  name: slice_2stage_class_45
  batch_size: 8
  learning_rate: 4.0
  lr_scales: [1.0, 0.5, 0.25, 0.025, 0.0025, 0.00025]
  momentum: 0.9
  weight_decay: 1e-6
  alpha_reg: [500, 1000, 2000, 2000, 2000, 2000]
  alpha_sigma: [1e-7, 1e-5, 1e-4, 1e-3, 1e-2, 1e-1] #lets see how aggressive we can be
  gpu_list: [0]
  epochs: 14
  key_epochs: [ 2, 4, 6, 8, 9 ]
  half_precision: False

dataset:
  path: ~/datasets/structure_core_unity
  is_npy: False
  workers: 8
  tgt_res: [ 1216, 896 ]
  slice_in:
    start: 100
    height: 128
  slice_out:
    start: 50
    height: 64

backbone:
  load_file: ""
  name: BackboneNoSlice3
  lines: 128
  slices: 1
  channels: [8, 16, 32]
  channels2: [32, 32, 64, 64]

regressor:
  load_file: ""
  name: Regv3
  ch_in: 64
  lines: 64
  bb: []
  classes: [16, 14, 12]
  padding: [0, 1, 2]
  class_bb: [[16], [16], [16]]
  superclasses: 336
  ch_reg: [32]
  msk: [128, 64, 32]
  regress_neighbours: 1
  reg_line_div: 4
  c3_line_div: 8 #8 might be over the top but lets see how we fare with this!
  close_far_separation: False
  per_line_sigma_weights: False


