training:
  name: 2stage_class_43_noacc_4
  batch_size: 2
  accumulation_steps: 1
  learning_rate: 4.0
  lr_scales: [1.0, 0.5, 0.25, 0.025, 0.0025]
  momentum: 0.9
  weight_decay: 1e-4
  alpha_reg: [500, 1000, 2000, 4000, 4000]
  alpha_sigma: [ 1e-7, 1e-5, 1e-4, 1e-3, 1e-3 ]
  sigma_mode: mask
  gpu_list: [0]
  epochs: 33
  key_epochs: [ 8, 16, 20, 24 ]
  half_precision: True

dataset:
  path: ~/datasets/structure_core_unity
  is_npy: False
  workers: 8
  tgt_res: [ 1216, 896 ]
  slice_in:
    start: 0
    height: 896
  slice_out:
    start: 0
    height: 448

backbone:
  load_file: ""
  name: BackboneU5Sliced # for the u-shaped backbone none of the parameters below has any value
  lines: 896
  slices: 4
  channels: [8, 16, 32]
  channels2: [32, 32, 64, 64]
  norm: batch

regressor:
  load_file: ""
  name: Regv3
  ch_in: 64
  lines: 448
  bb: []
  classes: [16, 14, 12]
  padding: [0, 1, 2]
  class_bb: [[16], [16], [16]]
  superclasses: 336
  ch_reg: [32]
  msk: [16, 8]
  regress_neighbours: 1
  reg_line_div: 4
  c3_line_div: 8 #8 might be over the top but lets see how we fare with this!
  close_far_separation: True
  sigma_mode: conv

