training:
  name: dis_real_lcn_c1920
  load_model: ""
  batch_size: 4
  learning_rate: 4.0
  lr_scales: [1.0, 0.5, 0.25, 0.12, 0.01]
  momentum: 0.9
  weight_decay: 1e-5 # 1e-6
  alpha_reg: [500, 1000, 2000, 2000, 2000]
  edge_weight: [0, 1, 2, 4, 20]
  gpu_list: [0]
  epochs: 5
  key_epochs: [ 1, 2, 3, 4 ]
  half_precision: True

dataset:
  path: ""
  is_npy: False
  workers: 8
  tgt_res: [ 432, 512 ]
  vertical_jitter: 0
  downsample_output: False
  dataset_type: depth_in_space
  slice_in:
    start: 0
    height: 512
  slice_out:
    start: 0
    height: 512

backbone:
  load_file: ""
  name: BackboneULight
  input_channels: 2
  lines: 512
  slices: 1
  norm: batch
  local_contrast_norm: True

regressor:
  load_file: ""
  name: Regressor
  lines: 512
  classes: [16, 12, 10]
  class_padding: [0, 2, 3]
  class_ch_in_offset: [0, 16, 32]
  class_ch_in: [64, 64, 64]
  class_ch: [[64, 32], [32], [32]] # [64, 32] for number 1
  reg_data_start: 64
  reg_superclasses: 640
  reg_ch_in: 32
  reg_ch: [32] # 32
  reg_overlap_neighbours: 1
  reg_shared_over_lines: 2 # two lines share the same weight for the regressor (maybe make this 4?)
  reg_pad: 0.1 # padding that is applied to the regression result/regression target
