training:
  name: full_74_j2_c1920
  load_model: ""
  batch_size: 8
  learning_rate: 4.0
  lr_scales: [1.0, 0.5, 0.25, 0.12, 0.01]
  momentum: 0.9
  weight_decay: 1e-5 # 1e-6
  alpha_reg: [500, 1000, 2000, 2000, 2000]
  edge_weight: [0, 1, 2, 4, 20]
  gpu_list: [0]
  epochs: 10
  key_epochs: [ 2, 4, 6, 8 ]
  half_precision: True

dataset:
  path: /media/simon/ssd_datasets/datasets/structure_core_unity_sequences
  is_npy: False
  workers: 8
  tgt_res: [ 1216, 896 ]
  vertical_jitter: 2
  downsample_output: True
  dataset_type: structure_core_unity_sequences
  slice_in:
    start: 0
    height: 896
  slice_out:
    start: 0
    height: 448


backbone:
  load_file: ""
  name: Backbone
  input_channels: 1
  lines: 896
  slices: 1
  channels: []
  kernel_sizes: []
  channels_sub: [16, 24, 32, 40, 48, 64, 64, 96] # [16, 32, 32, 64, 64]
  kernel_sizes_sub: [5, 3, 3, 3, 3, 3, 5, 3, 3]
  norm: batch
  local_contrast_norm: False

regressor:
  load_file: ""
  name: Regressor
  lines: 448
  classes: [16, 12, 10]
  class_padding: [0, 2, 3]
  class_ch_in_offset: [0, 16, 48]
  class_ch_in: [32, 32, 32]
  class_ch: [[32], [32], [32]]
  reg_data_start: 64
  reg_superclasses: 384 # TODO: SHOULD/COULD BE HIGHER! 240, 384, 480, 640 960
  reg_ch_in: 32
  reg_ch: [32] # 32
  reg_overlap_neighbours: 1
  reg_shared_over_lines: 2 # two lines share the same weight for the regressor (maybe make this 4?)
  reg_pad: 0.1 # padding that is applied to the regression result/regression target

